import {
  getDocSiteById,
  listMirroredPages,
  listSourcePages,
  upsertSiteLlmText
} from "./store";
import type { SiteLlmText } from "./types";

function siteBaseUrl(): string {
  return (process.env.SITE_BASE_URL || "").replace(/\/$/, "");
}

function absoluteMirrorUrl(siteSlug: string, lang: string, path: string): string {
  const relative = `/sites/${siteSlug}/${lang}${path}`;
  const baseUrl = siteBaseUrl();
  return baseUrl ? `${baseUrl}${relative}` : relative;
}

function markdownText(value: string): string {
  return value.replace(/\s+/g, " ").replace(/([\\[\]()])/g, "\\$1").trim();
}

function pageTitleFor(title: string | null, path: string): string {
  const normalized = title?.replace(/\s+/g, " ").trim();
  return markdownText(normalized || path || "/");
}

export async function generateSiteLlmText(siteId: string, lang: string): Promise<SiteLlmText> {
  const site = await getDocSiteById(siteId);
  if (!site) {
    throw new Error(`Site ${siteId} was not found.`);
  }

  const [sourcePages, mirroredPages] = await Promise.all([listSourcePages(site.id), listMirroredPages(site.id)]);
  const sourcesByPath = new Map(sourcePages.map((page) => [page.path, page]));
  const pages = mirroredPages
    .filter((page) => page.lang === lang)
    .sort((a, b) => a.path.localeCompare(b.path));

  if (pages.length === 0) {
    throw new Error(`No generated pages are available for ${lang}.`);
  }

  const hostname = new URL(site.entry_url).hostname.replace(/^www\./, "");
  const lines = [
    `# ${markdownText(hostname)} documentation`,
    "",
    "> Generated by 1Doc from a public documentation mirror.",
    "",
    `Source: ${site.entry_url}`,
    `Language: ${lang}`,
    `Pages: ${pages.length}`,
    "",
    "## Pages",
    ""
  ];

  for (const page of pages) {
    const source = sourcesByPath.get(page.path);
    lines.push(`- [${pageTitleFor(source?.title ?? null, page.path)}](${absoluteMirrorUrl(site.slug, lang, page.path)})`);
  }

  return upsertSiteLlmText({
    site_id: site.id,
    lang,
    content: `${lines.join("\n")}\n`,
    page_count: pages.length
  });
}

export async function generateSiteLlmTexts(siteId: string, langs?: string[]): Promise<SiteLlmText[]> {
  const site = await getDocSiteById(siteId);
  if (!site) {
    throw new Error(`Site ${siteId} was not found.`);
  }

  const targetLangs = langs?.length ? langs : site.target_langs;
  const results: SiteLlmText[] = [];
  for (const lang of targetLangs) {
    results.push(await generateSiteLlmText(site.id, lang));
  }
  return results;
}
